### PR TITLE
Add function to convert RSA private Jwks to public Jwks

### PR DESCRIPTION
**Pull request by lf-**
I needed this to be able to just store my private keys and derive public keys at use time, as someone running a server providing a jwk set endpoint.

Sorry if my coding is not the greatest, I'm relatively new to Haskell.

### CODE REVIEW

**Comment by lf-** [comment]
note: It's necessary to add this functionality in jose-jwt itself since the necessary data types to do it are not exported :)

**Comment by tekul** [comment]
Hi. Which types aren't exported? It looks like you could do this by just matching on the Jwk constructors? The function as it is will crash for a non Rsa key, which I'd rather avoid.

**Comment by lf-** [comment]
`JwkData`/`defJwk` is not exported (I also need `JwkBytes` I think), which are needed to get the public key info out of a `Jwk`. In general, the internals pieces of a Jwk are not accessible outside the library (which is a completely reasonable decision!).

**Comment by lf-** [comment]
As for the crashing, I agree that is not good API design. Is there a way I can make it so that the compiler will not accept any `Jwk`s that are not `RsaPrivateJwk` somehow? I guess I could make it return a `Maybe`.

**Comment by tekul** [comment]
I think those types are only needed for JSON encoding/decoding. Can't you just use the [constructor for an RSA public key](https://github.com/tekul/jose-jwt/blob/master/Jose/Jwk.hs#L57) directly? Something like:

```
case key of 
    RsaPrivateJwk privKey mId mUse mAlg ->
            RsaPubJwk (RSA.private_pub privKey) mId mUse mAlg
```

**Comment by lf-** [comment]
You are 100% correct. Thanks for the help!

**Pull request closed without merging**
