### PR TITLE
Add Num Instance

### PR DESCRIPTION
**Pull request by psibi**
Required subtraction on `IntDate` for one of our validations we do.

### CODE REVIEW

**Comment by tekul** [comment]
Thanks. I'd like to rename this type eventually since the name annoys me (I think it was initially just created as a newtype to prevent orphan `FromJSON`/`ToJSON` instances for `POSIXTime`).  It would be better called something like `POSIXSeconds`, possible with a type alias for the old name for compatibility.

I can merge this in the meantime though, but could you explain what the `nix` section in `stack.yaml` is for and whether it's appropriate here?

**Comment by psibi** [comment]
> I can merge this in the meantime though, but could you explain what the nix section in stack.yaml is for and whether it's appropriate here?

Totally forgot about the `nix` section. The `nix` section is required to make it work in NixOS, but I think it's ignored in other distributions. I can remove it if you think so.

**Comment by psibi** [comment]
@tekul Gentle ping...

**Comment by tekul** [comment]
Thanks. Sorry for the delay. Kind of busy with other non-Haskell stuff. I edited out the specific nix version and committed the rest of the change.

**Comment by psibi** [comment]
Thank you!

**Pull request closed without merging**
