### PR TITLE
added export of EcCurve type, this allows construction of Jwk's from …

### PR DESCRIPTION
**Pull request by CaptJakk**
this allows construction of Jwk's from scratch, I encountered the need for this when trying to translate pem encoded keys to Jwk's

### CODE REVIEW

**Comment by CaptJakk** [comment]
Looks like the 7.10 build is failing due to build issues with memory/basement?

**Comment by tekul** [comment]
Thanks. I've added your change and updated the build to drop support for ghc < 8, since cryptonite no longer supports earlier version.

**Comment by CaptJakk** [comment]
We good to merge this?

**Comment by tekul** [comment]
Uhhh, I already did. See my comment and commit above? Also I've released `0.8.0` so you should hopefully be good to go with that. Let me know if you have any further issues.

**Comment by CaptJakk** [comment]
whoops. My bad. I just saw the PR with an "open" status. We're all good, thanks.

**Pull request closed without merging**
